"""Update admin user with a freshly generated hash."""
import sqlite3

def update_admin_hash():
    # This hash was just generated by test_password.py
    new_hash = "$2b$12$oGw1lYBtVIR/FpDRVnMIp.DeGdIadIJqr205xJ41o9yX4w3Pa2vlO"
    
    conn = sqlite3.connect('fuelguard.db')
    cursor = conn.cursor()
    
    cursor.execute("UPDATE users SET hashed_password = ? WHERE username = 'admin'", (new_hash,))
    conn.commit()
    conn.close()
    
    print("Admin password hash updated!")
    print("Username: admin")
    print("Password: admin123")
    print("\nTry logging in now!")

if __name__ == "__main__":
    update_admin_hash()
